# Site Settings
title: Luis Huesca
description: Senior Unity Developer Portfolio
url: "https://danohuescaunity.github.io"
baseurl: ""

# Build Settings
markdown: kramdown
sass:
  style: compressed
  sass_dir: _sass

# Collections
collections:
  projects:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
